// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	handler "github.com/gilsuk/trulit-price-daily/collector/presenter/handler"
	mock "github.com/stretchr/testify/mock"
)

// factory is an autogenerated mock type for the factory type
type factory struct {
	mock.Mock
}

type factory_Expecter struct {
	mock *mock.Mock
}

func (_m *factory) EXPECT() *factory_Expecter {
	return &factory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields:
func (_m *factory) New() handler.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 handler.Handler
	if rf, ok := ret.Get(0).(func() handler.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.Handler)
		}
	}

	return r0
}

// factory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type factory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *factory_Expecter) New() *factory_New_Call {
	return &factory_New_Call{Call: _e.mock.On("New")}
}

func (_c *factory_New_Call) Run(run func()) *factory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *factory_New_Call) Return(_a0 handler.Handler) *factory_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *factory_New_Call) RunAndReturn(run func() handler.Handler) *factory_New_Call {
	_c.Call.Return(run)
	return _c
}

// newFactory creates a new instance of factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *factory {
	mock := &factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
