// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	handler "github.com/gilsuk/trulit-price-daily/collector/presenter/handler"
	mock "github.com/stretchr/testify/mock"
)

// Ifactory is an autogenerated mock type for the Ifactory type
type Ifactory struct {
	mock.Mock
}

type Ifactory_Expecter struct {
	mock *mock.Mock
}

func (_m *Ifactory) EXPECT() *Ifactory_Expecter {
	return &Ifactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields:
func (_m *Ifactory) New() handler.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 handler.Handler
	if rf, ok := ret.Get(0).(func() handler.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.Handler)
		}
	}

	return r0
}

// Ifactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type Ifactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *Ifactory_Expecter) New() *Ifactory_New_Call {
	return &Ifactory_New_Call{Call: _e.mock.On("New")}
}

func (_c *Ifactory_New_Call) Run(run func()) *Ifactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Ifactory_New_Call) Return(_a0 handler.Handler) *Ifactory_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Ifactory_New_Call) RunAndReturn(run func() handler.Handler) *Ifactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewIfactory creates a new instance of Ifactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIfactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ifactory {
	mock := &Ifactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
