with-expecter: True
recursive: True
all: True
outpkg: "mocks"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
packages:
  github.com/gilsuk/trulit-price-daily/collector/presenter/handler:
  github.com/gilsuk/trulit-price-daily/collector/worker/collector:
