// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	collector "github.com/gilsuk/trulit-price-daily/collector/worker/collector"
	mock "github.com/stretchr/testify/mock"
)

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

type Collector_Expecter struct {
	mock *mock.Mock
}

func (_m *Collector) EXPECT() *Collector_Expecter {
	return &Collector_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function with given fields: _a0
func (_m *Collector) Collect(_a0 collector.Request) {
	_m.Called(_a0)
}

// Collector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type Collector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - _a0 collector.Request
func (_e *Collector_Expecter) Collect(_a0 interface{}) *Collector_Collect_Call {
	return &Collector_Collect_Call{Call: _e.mock.On("Collect", _a0)}
}

func (_c *Collector_Collect_Call) Run(run func(_a0 collector.Request)) *Collector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(collector.Request))
	})
	return _c
}

func (_c *Collector_Collect_Call) Return() *Collector_Collect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Collector_Collect_Call) RunAndReturn(run func(collector.Request)) *Collector_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollector creates a new instance of Collector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Collector {
	mock := &Collector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
