// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// handler is an autogenerated mock type for the handler type
type handler struct {
	mock.Mock
}

type handler_Expecter struct {
	mock *mock.Mock
}

func (_m *handler) EXPECT() *handler_Expecter {
	return &handler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *handler) Execute() {
	_m.Called()
}

// handler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type handler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *handler_Expecter) Execute() *handler_Execute_Call {
	return &handler_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *handler_Execute_Call) Run(run func()) *handler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *handler_Execute_Call) Return() *handler_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *handler_Execute_Call) RunAndReturn(run func()) *handler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newHandler creates a new instance of handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *handler {
	mock := &handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
